name: Build and deploy Python project to Azure Function App - adpfe

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.11" # Versión de Python que deseas utilizar

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Necesario para actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Opcional: Añadir pruebas aquí si es necesario

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "venv/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Requerido para solicitar el JWT
      contents: read # Requerido para actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d ./app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Set SCM_DO_BUILD_DURING_DEPLOYMENT
        run: |
          az functionapp config appsettings set \
            --name adpfe \
            --resource-group <your-resource-group> \
            --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true

      - name: "Deploy to Azure Functions"
        uses: Azure/functions-action@v1
        with:
          app-name: "adpfe"
          package: ./app
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
